### ISSUE TITLE
Simplify PDN Connectivity Request handling - always reject

### ISSUE THREAD

**Issue by istorrs** [istorrs/srsRAN_4G#5]
## Summary

Simplifies the PDN Connectivity Request handling in the NAS layer by removing complex APN validation logic and defaulting to always send PDN Connectivity Reject responses.

## Changes Made

- Removed APN detection and validation logic from handle_pdn_connectivity_request
- Removed helper functions for APN string processing
- Simplified the function to always send PDN Connectivity Reject with cause LIBLTE_MME_ESM_CAUSE_SERVICE_OPTION_NOT_SUPPORTED
- Added console logging to match existing logging pattern
- Updated the reject message to indicate srsepc only supports default EPS bearers

## Files Changed

- srsepc/src/mme/nas.cc: Modified handle_pdn_connectivity_request function in NAS layer

## Testing

- Built successfully with CMake/make
- No compilation errors or warnings in the modified file

## Context

This reverts and simplifies the APN detection logic that was introduced in commit 4818f8e6c. The new approach provides a more straightforward handling of PDN connectivity requests by consistently rejecting them rather than attempting complex APN validation.
